### ISSUE TITLE
[ERROR] Im getting these error in my Minecraft 1.17.1 Server 

### ISSUE THREAD

**Issue by ghost** [Picono435/PicoJobs#121]
for a 1 day ago, im getting these error on my server, i had this plugin working but i dont know why now are broken

Error:

[16:19:13] [Server thread/ERROR]: Error occurred while enabling PicoJobs v1.0-beta-3d (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.gmail.picono435.picojobs.api.Type.getWhitelistType()" because "type" is null
	at com.gmail.picono435.picojobs.api.Job.<init>(Job.java:78) ~[?:?]
	at com.gmail.picono435.picojobs.PicoJobsPlugin.generateJobsFromConfig(PicoJobsPlugin.java:276) ~[?:?]
	at com.gmail.picono435.picojobs.PicoJobsPlugin.onEnable(PicoJobsPlugin.java:149) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:141) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:514) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:428) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Picono435** [comment]
Hello thank you for reporting the issue, could you please try with the latest dev build (https://github.com/Picono435/PicoJobs/actions)

**Comment by ghost** [comment]
how can i download it, i dont know how do that

**Comment by Picono435** [comment]
Hello, [this is the latest dev build](https://github.com/Picono435/PicoJobs/actions/runs/1373948550), just go into it scroll down and click Builds. It will download Builds.zip, then you just need to unzip and upload the JAR to your server :).

**Comment by ghost** [comment]
it says the same, type its null

[21:16:35] [Server thread/INFO]: [PicoJobs] Loading PicoJobs v49da386-DEV
[21:16:35] [Server thread/INFO]: [PicoJobs] Loading dependencies, this might take some minutes when ran for the first time...
[21:16:48] [Server thread/ERROR]: [PicoJobs] An error occuried while loading SLIMJAR, please contact a plugin developer with the following error:
[21:16:48] [Server thread/WARN]: UnresolvedDependencyException{dependency=org.mongodb:mongodb-driver-sync:4.3.3}
[21:16:48] [Server thread/WARN]: 	at com.gmail.picono435.picojobs.libs.slimjar.downloader.URLDependencyDownloader.lambda$download$0(URLDependencyDownloader.java:76)
[21:16:48] [Server thread/WARN]: 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[21:16:48] [Server thread/WARN]: 	at com.gmail.picono435.picojobs.libs.slimjar.downloader.URLDependencyDownloader.download(URLDependencyDownloader.java:76)
[21:16:48] [Server thread/WARN]: 	at com.gmail.picono435.picojobs.libs.slimjar.injector.helper.InjectionHelper.fetch(InjectionHelper.java:45)
[21:16:48] [Server thread/WARN]: 	at com.gmail.picono435.picojobs.libs.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:58)
[21:16:48] [Server thread/WARN]: 	at com.gmail.picono435.picojobs.libs.slimjar.injector.SimpleDependencyInjector.inject(SimpleDependencyInjector.java:52)
[21:16:48] [Server thread/WARN]: 	at com.gmail.picono435.picojobs.libs.slimjar.app.builder.InjectingApplicationBuilder.buildApplication(InjectingApplicationBuilder.java:63)
[21:16:48] [Server thread/WARN]: 	at com.gmail.picono435.picojobs.libs.slimjar.app.builder.ApplicationBuilder.build(ApplicationBuilder.java:462)
[21:16:48] [Server thread/WARN]: 	at com.gmail.picono435.picojobs.PicoJobsPlugin.onLoad(PicoJobsPlugin.java:101)
[21:16:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:408)
[21:16:48] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:233)
[21:16:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010)
[21:16:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[21:16:48] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Picono435** [comment]
It looks like the issue is different (it is related to the dependency manager now), could you please send your full logs? That would help a lot.

**Comment by ghost** [comment]
[2021-10-29-14.log](https://github.com/Picono435/PicoJobs/files/7446432/2021-10-29-14.log)

**Comment by Picono435** [comment]
Ok, thank you for sending me the logs could you please send me your PicoJobs folder now? So I can check if there is any configuration issue.

**Comment by Edy12alex** [comment]
[]((https://drive.google.com/drive/folders/100f0ZaEkQqUfy1xw1986y-MOmVy9xYR8?usp=sharing))

**Comment by ghost** [comment]
[https://drive.google.com/drive/folders/100f0ZaEkQqUfy1xw1986y-MOmVy9xYR8?usp=sharing](url)

**Comment by Picono435** [comment]
Line 34 in the jobs.yml file in the enchanter job, there is a type that does not exist. Make sure to check the list of valid job types [here](https://github.com/Picono435/PicoJobs/wiki/Types-of-jobs).

![image](https://user-images.githubusercontent.com/57836766/139532128-1c19b086-ff10-49a6-a0ee-ca82c8b3e079.png)

**Comment by ghost** [comment]
oh i dont see them sorry for wasting your time

**Comment by Picono435** [comment]
No problem, I am here to help, for questions like this you can actually join our [Discord](https://discord.gg/wQj53Hy) and just ask them, you will have a faster answer. 

As this issue has been fixed I will close the issue, if for some reason the issue persists make sure to re-open this issue or create another one.
