### ISSUE TITLE
[BUG] Issue with FILL type and powder snow

### ISSUE THREAD

**Issue by GazorHuman** [Picono435/PicoJobs#148]
**Describe the bug**
Some error in the console (it spam too)

**Screenshots and Logs**
[14:55:53 ERROR]: Could not pass event PlayerBucketFillEvent to PicoJobs v1.0-beta-5
java.lang.NoSuchFieldError: POWDER_SNOW
        at com.gmail.picono435.picojobs.listeners.jobs.FillListener.onFillBucket(FillListener.java:26) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor202.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:491) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerBucketFillEvent(CraftEventFactory.java:467) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.ItemBucket.a(ItemBucket.java:74) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.ItemStack.a(ItemStack.java:434) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:449) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1787) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:9) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Software Details:**
 - Server Software: Paper
 - Server Software Version: 1.16.5 build 794
 - Plugin Version 1.0-beta-5
 - Java Version: Java 16

**Comment by Picono435** [comment]
Ok, so I am not able to reproduce your issue. Can you send me your configuration folder?

**Comment by GazorHuman** [comment]
# IMPORTANT #
# Our plugin uses PlaceholderAPI to make placeholders, it's not required but if you want to use it you will need to add it
# A detailed wiki of our plugin can be found here: https://github.com/Picono435/wiki
# All the configurations are commented, but if you still need help check the wiki or send a message in our discord
#
# Remember that some configurations may be found in another files inside the settings folder.
# Here you will only find basic configurations
# IMPORTANT #

# DO NOT CHANGE THIS
config-version: "1.0-beta-5"
# Set to true if you want to enable DEBUG mode (It will log more messages on the console)
debug: false

#################################################################################
#                                                                               #
# Important configurations                                                      #
#                                                                               #
#################################################################################
# In this category there is a lot of important configurations that should be read and changed with your necessities
# Put here the language that you want to use!
# A list of all the possible languages can be found here: https://github.com/Picono435/PicoJobs/tree/master/src/main/resources/langs
# The translations can be INCORRECT or INCOMPLETE because they are made by the community, but you can always change them.
lang: "en-GB"
# Here you can put the name of your server, this message will appier in the start of all messages. To disable just put nothing.
prefix: "&6&lRenchCraft &r&7- "
# Here you can enable/disable the auto update
auto-update: true

#################################################################################
#                                                                               #
# Storage configurations                                                      #
#                                                                               #
#################################################################################
# In this configuration you can select the storage method that you want to use and config it.
storage:
  # Here is a list of storage methods that you can choose:
  #
  # | Remote databases - require connection information to be configured below
  # |=> MySQL
  # |=> MariaDB (recommended)
  # |=> PostgreSQL
  # |=> MongoDB
  #
  # |  Flatfile/local database - don't require any extra configuration
  # |=> H2 (recommended)
  # |=> SQLITE
  #
  # |  Readable & editable text files - don't require any extra configuration
  # |=> YAML (recommended)
  # |=> JSON
  # |=> HOCON
  storage-method: h2
  # Remote SQL databases (MySQL, MariaDB, PostgreSQL) configuration
  remote-sql:
    host: localhost
    port: 3306
    database: mydb
    username: root
    password: ""
    tablename: "jobplayers"
  # Remote MongoDB database configuration
  mongodb:
    # Here you need to put the MongoDB Connection URI
    # For more information check https://docs.mongodb.com/manual/reference/connection-string/
    URI: "mongodb+srv://<user>:<password>@mydatabases-host.mongodb.net/"
    database: "mcserver"
    collection: "jobplayers"

#################################################################################
#                                                                               #
# Basic configurations                                                          #
#                                                                               #
#################################################################################
# In this category you can change the basic configurations of the plugin
# What should happen when execute /jobs command?
# 1 = Ignore and send a message (This feature its not really useful yet, but it will be soon ;))
# 2 = Execute basic commands, enter a job, get salary etc... etc...
# 3 = Open Jobs Menu
jobs-action: 3
# What should be the salary cooldown in real life minutes 20 minutes = 1 minecraft day [DEFAULT: 600m=10h=30md]
salary-cooldown: 5
# Do you want it so you accept the job each time you complete a work or it automatically selects the work
auto-working: false

#################################################################################
#                                                                               #
# Commands allow                                                                #
#                                                                               #
#################################################################################
# In this category you can select all the commands that can only be used after a specific level (amount of works done)
commands:
  /examplecommand: 5

> Ok, so I am not able to reproduce your issue. Can you send me your configuration folder?

**Comment by Picono435** [comment]
Fixed issue in the lastest commit, thank you for reporting it. Be free to create another issue or re-open this one if the issue persists.
