### ISSUE TITLE
[BUG-AGAIN] i have last version from the actions

### ISSUE THREAD

**Issue by LeonMaximal1** [Picono435/PicoJobs#157]
[08:56:55 WARN]: Error connecting to the storage. The plugin will not work correctly.
[08:56:55 WARN]: org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-200]
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.get(DbException.java:205)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.get(DbException.java:181)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.get(DbException.java:170)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1511)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1490)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:350)
[08:56:55 WARN]: 	at PicoJobs-null.jar//com.gmail.picono435.picojobs.storage.sql.file.FlatfileStorageFactory.isWorking(FlatfileStorageFactory.java:130)
[08:56:55 WARN]: 	at PicoJobs-null.jar//com.gmail.picono435.picojobs.api.managers.PlayersManager.lambda$getJobPlayerFromStorage$2(PlayersManager.java:108)
[08:56:55 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[08:56:55 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[08:56:55 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:56:55 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[08:56:55 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[08:56:55 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:56:55 WARN]: Error connecting to the storage. The plugin will not work correctly.
[08:56:55 WARN]: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Connection is broken: "session closed" [90067-200]
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.get(DbException.java:205)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.get(DbException.java:181)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.engine.Session.prepareLocal(Session.java:634)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.engine.Session.prepareCommand(Session.java:595)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
[08:56:55 WARN]: 	at PicoJobs-null.jar//com.gmail.picono435.picojobs.storage.sql.file.FlatfileStorageFactory.getJob(FlatfileStorageFactory.java:79)
[08:56:55 WARN]: 	at PicoJobs-null.jar//com.gmail.picono435.picojobs.api.managers.PlayersManager.lambda$getJobPlayerFromStorage$2(PlayersManager.java:104)
[08:56:55 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[08:56:55 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[08:56:55 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:56:55 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[08:56:55 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[08:56:55 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:56:55 WARN]: Error connecting to the storage. The plugin will not work correctly.
[08:56:55 WARN]: java.util.concurrent.CancellationException
[08:56:55 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478)
[08:56:55 WARN]: 	at PicoJobs-null.jar//com.gmail.picono435.picojobs.api.managers.PlayersManager.lambda$getJobPlayerFromStorage$2(PlayersManager.java:114)
[08:56:55 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[08:56:55 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[08:56:55 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:56:55 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[08:56:55 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[08:56:55 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:56:55 WARN]: Error connecting to the storage. The plugin will not work correctly.
[08:56:55 WARN]: org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-200]
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.get(DbException.java:205)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.get(DbException.java:181)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.message.DbException.get(DbException.java:170)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1511)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:1211)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.jdbc.JdbcPreparedStatement.checkClosed(JdbcPreparedStatement.java:1738)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:1185)
[08:56:55 WARN]: 	at PicoJobs-null.jar//org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:106)
[08:56:55 WARN]: 	at PicoJobs-null.jar//com.gmail.picono435.picojobs.storage.sql.file.FlatfileStorageFactory.getMethodLevel(FlatfileStorageFactory.java:115)
[08:56:55 WARN]: 	at PicoJobs-null.jar//com.gmail.picono435.picojobs.api.managers.PlayersManager.lambda$getJobPlayerFromStorage$2(PlayersManager.java:106)
[08:56:55 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[08:56:55 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[08:56:55 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:56:55 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[08:56:55 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[08:56:55 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Picono435** [comment]
Could you check with the latest one to see if it still happens?

**Comment by LeonMaximal1** [comment]
THE SAME THING HAPPENS

În vin., 21 ian. 2022 la 20:07, Picono435 ***@***.***> a
scris:

**Comment by Picono435** [comment]
Are you sure you are running this one? https://github.com/Picono435/PicoJobs/suites/5019141989/artifacts/147699230 If you are please send me an updated log file.

**Comment by LeonMaximal1** [comment]
[image: image.png]

În vin., 21 ian. 2022 la 20:25, Picono435 ***@***.***> a
scris:

**Comment by LeonMaximal1** [comment]
now working


În vin., 21 ian. 2022 la 21:24, LeonMax ***@***.***> a
scris:

**Comment by LeonMaximal1** [comment]
[21:26:48 WARN]: Retrieving jobs from the config...
[21:26:48 WARN]: [STDERR] [Server thread] INFO
com.gmail.picono435.picojobs.libs.zaxxer.hikari.HikariDataSource -
HikariPool-1 - Starting...
[21:26:48 WARN]: Nag author(s): '[[Picono435]]' of 'PicoJobs' about their
usage of System.out/err.print. Please use your plugin's logger instead
(JavaPlugin#getLogger).
[21:26:48 WARN]: [STDERR] [Server thread] INFO
com.gmail.picono435.picojobs.libs.zaxxer.hikari.HikariDataSource -
HikariPool-1 - Start completed.
[21:26:48 WARN]: The plugin was succefully enabled

În vin., 21 ian. 2022 la 21:27, LeonMax ***@***.***> a
scris:

**Comment by Picono435** [comment]
The confirmation for this issue being fixed is finally done. If for some reason the issue persists make sure to re-open the issue or create another one.

**Comment by LeonMaximal1** [comment]
AGAIN

În vin., 21 ian. 2022 la 21:38, Picono435 ***@***.***> a
scris:

**Comment by Picono435** [comment]
Can you send me the new log please?

**Comment by LeonMaximal1** [comment]
În dum., 23 ian. 2022 la 16:37, Picono435 ***@***.***> a
scris:

**Comment by Picono435** [comment]
Sorry I don't think I can open the logs?

**Comment by Picono435** [comment]
Because this issue hasn't had any activity for a while now it will be closed. If you have any further issues related to this issue make sure to re-open it.
