### ISSUE TITLE
Editor and Max Salary doesnt work

### ISSUE THREAD

**Issue by Skyluke091** [Picono435/PicoJobs#348]
First Problem: When i use the "/jobsadmin editor" command i shows the message "An Internal Error occurred while attempting to perform this command"

Second Problem: I tried to put in a max Salary of 50.000$ but it doesent work in game my salary goes above 50.000$

First Problem:
1. Put "/jobsadmin editor" in Chat
2. See error

Second Problem: 
1. Go to Config
2. Put Max Salary to 50.000$
3. Test ingame

**Expected behavior**
First Problem: It should give me a link to a Website which has the Editor connectet to the Game

Second Problem: It should stop to add Salary to my salary if the limit is reached

**Software Details:**
 - Server Software: Paper
 - Server Software Version: Paper 1.20.4
 - Plugin Version: PicoJobs-1.0-beta-7a.jar
 - Java Version: Java 17

**Screenshots and Logs**
issued server command: /jobsadmin editor
[16:07:38 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'jobsadmin' in plugin PicoJobs v1.0-beta-7a
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-454]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-454]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-454]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-454]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)'
        at com.gmail.picono435.picojobs.libs.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:178) ~[PicoJobs-1.0-beta-7a.jar:?]
        at com.gmail.picono435.picojobs.libs.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:471) ~[PicoJobs-1.0-beta-7a.jar:?]
        at com.gmail.picono435.picojobs.libs.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:375) ~[PicoJobs-1.0-beta-7a.jar:?]
        at com.gmail.picono435.picojobs.libs.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:348) ~[PicoJobs-1.0-beta-7a.jar:?]
        at com.gmail.picono435.picojobs.libs.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[PicoJobs-1.0-beta-7a.jar:?]
        at com.gmail.picono435.picojobs.libs.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[PicoJobs-1.0-beta-7a.jar:?]
        at com.gmail.picono435.picojobs.libs.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597) ~[PicoJobs-1.0-beta-7a.jar:?]
        at com.gmail.picono435.picojobs.utils.DocConverter.convertYamlToJson(DocConverter.java:59) ~[PicoJobs-1.0-beta-7a.jar:?]
        at com.gmail.picono435.picojobs.commands.JobsAdminCommand.createEditor(JobsAdminCommand.java:320) ~[PicoJobs-1.0-beta-7a.jar:?]
        at com.gmail.picono435.picojobs.commands.JobsAdminCommand.onCommand(JobsAdminCommand.java:211) ~[PicoJobs-1.0-beta-7a.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more

**Comment by Picono435** [comment]
First problem: PicoJobs Editor is still on the works. Althought it should not send an internal error message (I will check that one) it still should not be accessible for now. PicoJobs Editor will probably be released later this year.

Second problem: The max-salary option doesn't actually limit the "balance" you have to collect. It only limits the amount of money you can earn by doing a work. Let me know if this is still an issue.

**Comment by Skyluke091** [comment]
Ohhh ok is there a function to set the max salary?

**Comment by Picono435** [comment]
The max salary you have in the balance? (The one in the redstone torch by default)

**Comment by Skyluke091** [comment]
No i mean the maximum Amount you can collect from one Salary

**Comment by Picono435** [comment]
So there is a max-salary option that limits the amount of money you can earn per work.

There is no max-salary for the amount of money you have in your PicoJobs redstone torch balance.

**Comment by Skyluke091** [comment]
Would it be an Option to implement that Feature into the Plugin?

**Comment by Picono435** [comment]
I can do some kind of max-balance yeah. Will take a deeper look into it.

**Comment by Skyluke091** [comment]
Thanks
