### ISSUE TITLE
[BUG]  1.21 Not Working Jobs!

### ISSUE THREAD

**Issue by zevkev** [Picono435/PicoJobs#351]
Gui Buttons not working also freeziong, no payout

org.bukkit.command.CommandException: Unhandled exception executing command 'jobsadmin' in plugin PicoJobs v1.0-beta-7a
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchCommand(CraftServer.java:913) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at org.bukkit.craftbukkit.v1_21_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:414) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1842) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$7(PlayerConnection.java:1818) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)'
at com.gmail.picono435.picojobs.libs.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:178) ~[?:?]
at com.gmail.picono435.picojobs.libs.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:471) ~[?:?]
at com.gmail.picono435.picojobs.libs.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:375) ~[?:?]
at com.gmail.picono435.picojobs.libs.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:348) ~[?:?]
at com.gmail.picono435.picojobs.libs.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[?:?]
at com.gmail.picono435.picojobs.libs.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[?:?]
at com.gmail.picono435.picojobs.libs.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597) ~[?:?]
at com.gmail.picono435.picojobs.utils.DocConverter.convertYamlToJson(DocConverter.java:59) ~[?:?]
at com.gmail.picono435.picojobs.commands.JobsAdminCommand.createEditor(JobsAdminCommand.java:320) ~[?:?]
at com.gmail.picono435.picojobs.commands.JobsAdminCommand.onCommand(JobsAdminCommand.java:211) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
... 28 more

**Describe the bug**

**To Reproduce**
1. Go to 'start server 1.21'
2. Click on 'Jobs'
3. Scroll down to 'choose one and do it try to  payout or get salary'

**Expected behavior**

**Screenshots and Logs**
If applicable, add screenshots or logs of your server to help explain your problem.

**Additional context**

**Comment by Picono435** [comment]
This has been fixed in the latest builds but they were still not published. You can download it [here](https://github.com/Picono435/PicoJobs/actions/runs/9430272504). Deleting the database or a manual migration of the database might be needed if you use H2 as the storage method.

As soon as I publish the release I will close this issue.
