### ISSUE TITLE
[BUG] Default SQL configuration is invalid and Remote SQL connector seems to be broken

### ISSUE THREAD

**Issue by burdoto** [Picono435/PicoJobs#364]
**Describe the bug**
MariaDB database connection unable to load up, yet plugin claims it started successfully, then spits a ton of exceptions

**To Reproduce**
- Set up MariaDB Database
- Restart server (reloading wouldn't do it right)

**Expected behavior**
The MariaDB connector should load up normally.

**Screenshots and Logs**
The exception shown during plugin initialization:
```
[05:02:38] [Server thread/INFO]: [PicoJobs] Enabling PicoJobs v1.0-pre
[05:02:38] [Server thread/INFO]: [PicoJobs] Plugin created by: picono435. Thank you for using it
[05:02:38] [Server thread/INFO]: [PicoJobs] Registered EXP economy implementation.
[05:02:38] [Server thread/INFO]: [PicoJobs] Registered COMMAND economy implementation.
[05:02:38] [Server thread/INFO]: [PicoJobs] Registered ITEM economy implementation.
[05:02:38] [Server thread/INFO]: [PicoJobs] Registered VAULT economy implementation.
[05:02:38] [Server thread/INFO]: [PicoJobs] Registered BIOME work zone implementation.
[05:02:38] [Server thread/INFO]: [PicoJobs] Registered WORLD work zone implementation.
[05:02:38] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: job [1.0-pre]
[05:02:38] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: jobplayer [1.0-pre]
[05:02:38] [Server thread/INFO]: [PicoJobs] Generating jobs from the configuration files...
[05:02:38] [Server thread/INFO]: [PicoJobs] Retrieving jobs from the config...
[05:02:38] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[05:02:38] [Server thread/ERROR]: [com.zaxxer.hikari.util.PropertyElf] Property databaseName does not exist on target class org.mariadb.jdbc.MariaDbDataSource
[05:02:38] [Server thread/ERROR]: [PicoJobs] Error connecting to the storage. The plugin will not work correctly.
[05:02:38] [Server thread/WARN]: java.lang.RuntimeException: Property databaseName does not exist on target class org.mariadb.jdbc.MariaDbDataSource
[05:02:38] [Server thread/WARN]: 	at picojobs.jar//com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:135)
[05:02:38] [Server thread/WARN]: 	at picojobs.jar//com.zaxxer.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:59)
[05:02:38] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
[05:02:38] [Server thread/WARN]: 	at java.base/java.util.Properties.forEach(Properties.java:1467)
[05:02:38] [Server thread/WARN]: 	at picojobs.jar//com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:54)
[05:02:38] [Server thread/WARN]: 	at picojobs.jar//com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:328)
[05:02:38] [Server thread/WARN]: 	at picojobs.jar//com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
[05:02:38] [Server thread/WARN]: 	at picojobs.jar//com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
[05:02:38] [Server thread/WARN]: 	at picojobs.jar//com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[05:02:38] [Server thread/WARN]: 	at picojobs.jar//com.gmail.picono435.picojobs.common.storage.sql.MariaDbStorage.initializeStorage(MariaDbStorage.java:24)
[05:02:38] [Server thread/WARN]: 	at picojobs.jar//com.gmail.picono435.picojobs.common.storage.StorageManager.initializeStorageFactory(StorageManager.java:69)
[05:02:38] [Server thread/WARN]: 	at picojobs.jar//com.gmail.picono435.picojobs.common.PicoJobsMain.init(PicoJobsMain.java:67)
[05:02:38] [Server thread/WARN]: 	at picojobs.jar//com.gmail.picono435.picojobs.common.PicoJobsCommon.onEnable(PicoJobsCommon.java:80)
[05:02:38] [Server thread/WARN]: 	at picojobs.jar//com.gmail.picono435.picojobs.bukkit.PicoJobsBukkit.onEnable(PicoJobsBukkit.java:48)
[05:02:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[05:02:38] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[05:02:38] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[05:02:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[05:02:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641)
[05:02:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590)
[05:02:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[05:02:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[05:02:38] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[05:02:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[05:02:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[05:02:38] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[05:02:38] [Server thread/INFO]: [PicoJobs] The plugin was successfully loaded.
[05:02:38] [Server thread/INFO]: [PicoJobs] You are using the latest version of the plugin.
```

**Software Details:**
 - Server Software: Paper 
 - Server Software Version: 1.21.1, build 131
 - Plugin Version: 1.0-pre
 - Java Version: openjdk 21.0.5

**Secondary Steps:**
Change the `database` attribute in the `remote-sql` configuration section to `databaseName`.
After doing so, the startup exception changes to this:
```
[05:07:50] [Server thread/INFO]: [PicoJobs] Enabling PicoJobs v1.0-pre
[05:07:50] [Server thread/INFO]: [PicoJobs] Plugin created by: picono435. Thank you for using it
[05:07:50] [Server thread/INFO]: [PicoJobs] Registered EXP economy implementation.
[05:07:50] [Server thread/INFO]: [PicoJobs] Registered COMMAND economy implementation.
[05:07:50] [Server thread/INFO]: [PicoJobs] Registered ITEM economy implementation.
[05:07:50] [Server thread/INFO]: [PicoJobs] Registered VAULT economy implementation.
[05:07:50] [Server thread/INFO]: [PicoJobs] Registered BIOME work zone implementation.
[05:07:50] [Server thread/INFO]: [PicoJobs] Registered WORLD work zone implementation.
[05:07:50] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: job [1.0-pre]
[05:07:50] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: jobplayer [1.0-pre]
[05:07:50] [Server thread/INFO]: [PicoJobs] Generating jobs from the configuration files...
[05:07:50] [Server thread/INFO]: [PicoJobs] Retrieving jobs from the config...
[05:07:50] [Server thread/ERROR]: [PicoJobs] Error connecting to the storage. The plugin will not work correctly.
[05:07:50] [Server thread/WARN]: java.lang.NullPointerException
[05:07:50] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
[05:07:50] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
[05:07:50] [Server thread/WARN]: 	at java.base/java.util.Properties.put(Properties.java:1346)
[05:07:50] [Server thread/WARN]: 	at picojobs.jar//com.zaxxer.hikari.HikariConfig.addDataSourceProperty(HikariConfig.java:446)
[05:07:50] [Server thread/WARN]: 	at picojobs.jar//com.gmail.picono435.picojobs.common.storage.sql.MariaDbStorage.initializeStorage(MariaDbStorage.java:20)
[05:07:50] [Server thread/WARN]: 	at picojobs.jar//com.gmail.picono435.picojobs.common.storage.StorageManager.initializeStorageFactory(StorageManager.java:69)
[05:07:50] [Server thread/WARN]: 	at picojobs.jar//com.gmail.picono435.picojobs.common.PicoJobsMain.init(PicoJobsMain.java:67)
[05:07:50] [Server thread/WARN]: 	at picojobs.jar//com.gmail.picono435.picojobs.common.PicoJobsCommon.onEnable(PicoJobsCommon.java:80)
[05:07:50] [Server thread/WARN]: 	at picojobs.jar//com.gmail.picono435.picojobs.bukkit.PicoJobsBukkit.onEnable(PicoJobsBukkit.java:48)
[05:07:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[05:07:50] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[05:07:50] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[05:07:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[05:07:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641)
[05:07:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590)
[05:07:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[05:07:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[05:07:50] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[05:07:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[05:07:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[05:07:50] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[05:07:50] [Server thread/INFO]: [PicoJobs] The plugin was successfully loaded.
[05:07:50] [Server thread/INFO]: [PicoJobs] You are using the latest version of the plugin.
```

**Comment by Picono435** [comment]
This issue has been fixed in the latest commit. A new release will launch with the new fix very soon.
