### ISSUE TITLE
[BUG] H2 database error

### ISSUE THREAD

**Issue by DuAnti7423** [Picono435/PicoJobs#54]
**Describe the bug**
Error on Startup

**To Reproduce**

**Expected behavior**

**Screenshots and Logs**
[12:41:31] [Craft Scheduler Thread - 14/ERROR]: [PicoJobs] Error connecting to the storage. The plugin will not work correctly.
[12:41:31] [Craft Scheduler Thread - 14/WARN]: org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.h2.message.DbException.get(DbException.java:205)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.h2.message.DbException.get(DbException.java:181)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.h2.message.DbException.get(DbException.java:170)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1568)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:1237)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.h2.jdbc.JdbcPreparedStatement.checkClosed(JdbcPreparedStatement.java:1829)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:1211)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:107)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at com.gmail.picono435.picojobs.storage.sql.file.FlatfileStorageFactory.getJob(FlatfileStorageFactory.java:62)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at com.gmail.picono435.picojobs.api.managers.PlayersManager.lambda$getJobPlayerFromStorage$0(PlayersManager.java:84)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:41:31] [Craft Scheduler Thread - 14/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[12:41:31] [Craft Scheduler Thread - 6/ERROR]: [PicoJobs] Error connecting to the storage. The plugin will not work correctly.
[12:41:31] [Craft Scheduler Thread - 6/WARN]: java.util.concurrent.CancellationException
[12:41:31] [Craft Scheduler Thread - 6/WARN]: 	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2276)
[12:41:31] [Craft Scheduler Thread - 6/WARN]: 	at com.gmail.picono435.picojobs.api.managers.PlayersManager.lambda$getJobPlayerFromStorage$0(PlayersManager.java:94)
[12:41:31] [Craft Scheduler Thread - 6/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[12:41:31] [Craft Scheduler Thread - 6/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[12:41:31] [Craft Scheduler Thread - 6/WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[12:41:31] [Craft Scheduler Thread - 6/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:41:31] [Craft Scheduler Thread - 6/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:41:31] [Craft Scheduler Thread - 6/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Software Details:**
 - Server Software: [e.g. Spigot, Bukkit, Magma, PaperSpigot] Paper
 - Server Software Version [e.g. Paper 1.16.5-526, Spigot 1.8.8, Magma Dev HEAD-1bc8635] This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
 - Plugin Version [e.g. 1.0-beta-1b, 1.0-beta-1bc] 1.0-beta-2a
 - Java Version: [e.g.  Version 8 Update 28) Java 8, pterodactyl docker image

**Additional context**

**Comment by Picono435** [comment]
This issue is under investigation you can try change the storage method to SQL to see if it fixes the issue for now.

**Comment by Picono435** [comment]
Hello, could you let me know your OS? If it is Windows, Ubuntu, etc...

**Comment by DuAnti7423** [comment]
Debian

**Comment by DuAnti7423** [comment]
For this quick questions, u could ask me on your Discord xD

**Comment by Picono435** [comment]
Can you please let me know your discord.

**Comment by Picono435** [comment]
Thank you for the information, I will indeed xD.

**Comment by Picono435** [comment]
If you could please check with the version [1.0-beta-3](https://github.com/Picono435/PicoJobs/releases/tag/1.0-beta-3) that is the latest version of the plugin to see if this issue is fixed I would be really appreciated it. Let me know here if it works or not.

**Comment by Picono435** [comment]
This issue will be closed now because no answer from the author was given.
